### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by nickson91** [apdmatos/instagram-unfollow#1]
"raise ClientLoginError('Unable to login')
instagram_web_api.errors.ClientLoginError: Unable to login"

how can i solve this

**Comment by apdmatos** [comment]
It seems to me that your credentials are invalid. did you try to login in the web version?
Just tested it in my machine and it works just fine

**Comment by nickson91** [comment]
I tried. and yes my password is true. can it be anything else? im using my instagram username

**Comment by apdmatos** [comment]
The only thing I can do is go on zoom with you, and try to help

**Comment by nickson91** [comment]
I used another module for now. Thank you very much for your helpfullness bro, kudos from an internet friend
